{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lens-selector-fhir.fullname" . }}
  labels:
    {{- include "lens-selector-fhir.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
